### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by aa2858** [aws-samples/amazon-rekognition-engagement-meter#43]
Thank you very much @matteofigus for your help.

We finally able to deploy the modified version in our environment.  The issue now is getting the below error when running rekognition and I guessing around api gateway configurations.  I opened a support ticket as well.  Just wanted to check on the side with you.

Access to XMLHttpRequest at 'https://w0mqswjzkk.execute-api.us-east-1.amazonaws.com/PROD/people' from origin 'https://d1wkp6ddp65zn.cloudfront.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Thanks,
Adams

**Comment by matteofigus** [comment]
Hi Adams, thanks for submitting the issue.

We did a bit of digging. When the APIGW returns a response, it should send a wildcard for the `Access-Control-Allow-Origin` header: https://github.com/aws-samples/amazon-rekognition-engagement-meter/blob/master/src/cfn/template.yaml#L520

My assumption is that something may be wrong and the API is returning a non 200 code, not matching the mapping and showing a CORS error. 
We have a plan for that (we'll add mappers for 4xx and 5xx status codes soon), but in the meanwhile, I recommend opening the API Gateway Web Interface and trying to test the `GET /people` endpoint. If something was changed on the IAM side, for instance, perhaps the API Gateway may be having troubles accessing Dynamo and you may spot an interesting error message there.

I'll keep you on the loop.
Thanks for your patience.

**Comment by matteofigus** [comment]
Hi @aa2858, as anticipated in my previous comment, we published a new change that should allow you to have better error descriptions when having a non-200 response from the API. Would you be able to test the new version?

I am hoping that will help to troubleshoot the issue.

**Comment by matteofigus** [comment]
I haven't heard anything new, so I am closing it, but please re-open if the problem persists. Thanks.
