### ISSUE TITLE
Persons recognized are not called out in the bounding box

### ISSUE THREAD

**Issue by cslattery117** [aws-samples/amazon-rekognition-engagement-meter#91]
hi 
If I upload a pic and this person is recognized in the video stream it doesn't put their name around the box , just leaves it as "Person 1" or whatever .  It does recognize the picture correctly as the name pops up on the right .     Which is correct, please ?  I'd like it to do so, or is this an exercise for the reader ?  My React skills are not very good.

**Comment by matteofigus** [comment]
This is correct. The demo is just to show the art of the possible, if someone wants to achieve that behaviour some code changes are needed.
